server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dealership
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

logging:
  level:
    liquibase: DEBUG

auction-url: http://127.0.0.1:8081/api

grpc:
  server:
    port: 9090