version: '3.9'
services:
  tpr-postgres:
    image: postgres:16.2
    container_name: tpr-postgres
    restart: always
    environment:
      POSTGRES_DB: tpr
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - tpr-postgres-volume:/var/lib/postgresql/data

volumes:
  tpr-postgres-volume: