version: '3.9'
services:
  postgres-dealership:
    image: postgres:16.2
    container_name: postgres-dealership
    restart: always
    environment:
      POSTGRES_DB: dealership
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-dealership-volume:/var/lib/postgresql/data

  auction-dealership:
    image: postgres:16.2
    container_name: postgres-auction
    restart: always
    environment:
      POSTGRES_DB: auction
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "6433:5432"
    volumes:
      - postgres-auction-volume:/var/lib/postgresql/data

volumes:
  postgres-dealership-volume:
  postgres-auction-volume:
