server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:6433/auction
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    liquibase: DEBUG

dealership-url: http://127.0.0.1:8080/api

grpc:
  client:
    vehicle:
      address: static://localhost:9090
      negotiation-type: plaintext